version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1554505294
layout:
  /container-body/:
    -
      -
        '/bodysidebar/ 20':
          -
            - logo-9680
          -
            - simplecontent-7568
          -
            - verticalmenu-2655
          -
            - social-9516
      -
        '/top/ 80':
          -
            - system-messages-9828
        /navigation/: {  }
        /slideshow/: {  }
        /header/: {  }
        /above/: {  }
        /feature/: {  }
        /showcase/: {  }
        /utility/: {  }
        /container-main/:
          -
            -
              'sidebar 20':
                -
                  - position-position-9414
            -
              'mainbar 60':
                -
                  - system-content-1120
            -
              'aside 20':
                -
                  - position-position-8807
        /expanded/: {  }
        /extension/: {  }
        /bottom/: {  }
        /footer/:
          -
            - 'simplemenu-2324 25'
            - 'simplemenu-8319 25'
            - 'simplemenu-2461 50'
        /copyright/:
          -
            - copyright-6444
  offcanvas:
    -
      - mobile-menu-2576
structure:
  bodysidebar:
    type: section
    title: 'Body Sidebar'
    attributes:
      boxed: ''
      class: ''
  top:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  navigation:
    type: section
    attributes:
      boxed: '3'
      class: ''
      variations: section-horizontal-paddings
  slideshow:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  header:
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  above:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  feature:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  showcase:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: section-horizontal-paddings
  aside:
    attributes:
      class: ''
  container-main:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  extension:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  bottom:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  footer:
    attributes:
      boxed: ''
      class: ''
      variations: ''
  copyright:
    type: section
    attributes:
      boxed: ''
      class: ''
  container-body:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      swipe: '0'
content:
  logo-9680:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://pages/all/img-01.jpg'
      text: ''
      title: ''
      class: avatar-logo
    block:
      variations: 'center nomarginbottom nopaddingbottom'
  simplecontent-7568:
    title: 'Simple Content'
    attributes:
      class: ''
      title: ''
      items:
        -
          layout: standard
          created_date: ''
          content_title: 'Jericho James'
          author: ''
          leading_content: 'Freelance Musician'
          main_content: ''
          readmore_label: ''
          readmore_link: ''
          readmore_class: ''
          readmore_target: _self
          title: 'Avatar Desc'
    block:
      variations: 'center nomargintop nopaddingtop'
  verticalmenu-2655:
    title: 'Vertical Menu'
    block:
      class: g-vnavigation-container
      variations: 'nopaddingtop nomargintop center'
  social-9516:
    block:
      class: social-sidebar
      variations: 'center nopaddingleft nopaddingright'
  position-position-9414:
    title: Sidebar
    attributes:
      key: sidebar
  position-position-8807:
    title: Aside
    attributes:
      key: aside
  simplemenu-2324:
    title: 'Simple Menu'
    attributes:
      menus:
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'About me'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'My articles'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Case Studies'
            -
              icon: ''
              link: '#'
              target: _blank
              title: Blog
          title: 'Quick Links'
  simplemenu-8319:
    title: 'Simple Menu'
    attributes:
      menus:
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: Medium
            -
              icon: ''
              link: '#'
              target: _blank
              title: WordPress
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'New York Times'
            -
              icon: ''
              link: '#'
              target: _blank
              title: Forbes
          title: Elsewhere
  simplemenu-2461:
    title: 'Simple Menu'
    attributes:
      menus:
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'The Amateur''s Guide to Visiting an Art Museum'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Scientist Are Working on a Pill for Loneliness'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'How a Stroke Turned a 63-year-old Into a Rap Legend'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Reclaiming My Writer''s Voice'
          title: 'Latest articles'
  copyright-6444:
    attributes:
      date:
        start: ''
        end: ''
      owner: 'by <span>Jericho James</span>. All rights reserved. Theme by <span>RocketTheme.</span>'
  mobile-menu-2576:
    title: 'Mobile Menu'
